/**
 * Generates platform-specific scheduling configuration for unattended Bones runs.
 * Supports macOS launchd (plist) and Linux cron.
 */

import { existsSync } from "node:fs";
import { homedir } from "node:os";
import { join, resolve } from "node:path";

/** Preset scheduling configurations. */
export type SchedulePreset = "nightly" | "weekly";

/** Configuration for generating a schedule entry. */
export interface ScheduleConfig {
	/** Path to the project to review. */
	readonly projectPath: string;
	/** Preset schedule or null for custom. */
	readonly preset?: SchedulePreset;
	/** Custom cron expression (ignored if preset is set). */
	readonly cron?: string;
	/** Hunt category (default: bugs). */
	readonly category?: string;
	/** Number of agents (default: 2). */
	readonly agents?: number;
	/** Target score (default: 5). */
	readonly target?: number;
	/** Max rounds (default: 2). */
	readonly maxRounds?: number;
	/** Path to bones binary (auto-detected). */
	readonly bonesPath?: string;
}

/** Result of schedule generation. */
export interface ScheduleResult {
	readonly platform: "macos" | "linux";
	readonly instructions: string;
	readonly files: ReadonlyArray<{
		readonly path: string;
		readonly content: string;
	}>;
}

/**
 * Detects the current platform for scheduling purposes.
 *
 * @returns "macos" for Darwin, "linux" for Linux
 * @throws Error for unsupported platforms
 */
function detectPlatform(): "macos" | "linux" {
	switch (process.platform) {
		case "darwin":
			return "macos";
		case "linux":
			return "linux";
		default:
			throw new Error(
				`Unsupported platform: ${process.platform}. Only macOS and Linux are supported.`,
			);
	}
}

/**
 * Resolves the path to the bones binary.
 * Checks common locations: global npm, bun, and local dev.
 *
 * @param override - Explicit path from user
 * @returns Absolute path to bones binary
 */
function resolveBinaryPath(override?: string): string {
	if (override) return resolve(override);

	// Check if bones is in PATH
	const which = Bun.spawnSync(["which", "bones"]);
	if (which.exitCode === 0) {
		return which.stdout.toString().trim();
	}

	// Fallback to bun run dev
	return "bun run dev --";
}

/**
 * Builds the bones play command string for a given config.
 *
 * @param config - Schedule configuration
 * @param category - Hunt category for this run
 * @returns Full command string
 */
function buildPlayCommand(config: ScheduleConfig, category: string): string {
	const bones = resolveBinaryPath(config.bonesPath);
	const parts = [
		bones,
		"play",
		`--path ${resolve(config.projectPath)}`,
		`-c ${category}`,
		`-a ${config.agents ?? 2}`,
		`-t ${config.target ?? 5}`,
		`-m ${config.maxRounds ?? 2}`,
		"--output json",
	];
	return parts.join(" ");
}

/**
 * Generates a wrapper shell script for scheduled execution.
 * Handles logging, error capture, and clean exit.
 *
 * @param config - Schedule configuration
 * @param category - Hunt category
 * @returns Shell script content
 */
function buildWrapperScript(config: ScheduleConfig, category: string): string {
	const logDir = join(homedir(), ".bones", "nightly");
	const playCmd = buildPlayCommand(config, category);

	return `#!/bin/bash
set -euo pipefail

# Bones scheduled run — ${category}
# Generated by: bones schedule
DATE="$(date +%Y-%m-%d_%H-%M)"
LOG_DIR="${logDir}/$DATE"
mkdir -p "$LOG_DIR"

echo "[$(date)] Starting bones ${category} hunt for ${resolve(config.projectPath)}" >> "$LOG_DIR/run.log"

${playCmd} \\
  > "$LOG_DIR/events.ndjson" 2>"$LOG_DIR/stderr.log"

EXIT_CODE=$?

if [ $EXIT_CODE -eq 0 ]; then
  GAME_ID=$(head -1 "$LOG_DIR/events.ndjson" | grep -o '"gameId":"[^"]*"' | cut -d'"' -f4)
  echo "[$(date)] Game complete: $GAME_ID" >> "$LOG_DIR/run.log"
else
  echo "[$(date)] Game failed with exit code $EXIT_CODE" >> "$LOG_DIR/run.log"
fi

# Rotate old logs (keep last 30 days)
find "${logDir}" -maxdepth 1 -type d -mtime +30 -exec rm -rf {} + 2>/dev/null || true

exit $EXIT_CODE
`;
}

/**
 * Maps preset names to category-day assignments.
 *
 * @param preset - Preset name
 * @returns Array of [dayOfWeek, category] tuples
 */
function getPresetSchedule(
	preset: SchedulePreset,
): ReadonlyArray<readonly [number, string]> {
	switch (preset) {
		case "nightly":
			// Mon/Wed = bugs, Tue/Thu = doc_drift, Fri = security
			return [
				[1, "bugs"],
				[2, "doc_drift"],
				[3, "bugs"],
				[4, "doc_drift"],
				[5, "security"],
			];
		case "weekly":
			// Sunday at midnight — full bugs hunt
			return [[0, "bugs"]];
	}
}

/**
 * Generates a macOS launchd plist for scheduled execution.
 *
 * @param label - Plist label identifier
 * @param scriptPath - Path to the wrapper script
 * @param dayOfWeek - Day of week (0=Sunday)
 * @param hour - Hour to run (24h)
 * @returns Plist XML content
 */
function generatePlist(
	label: string,
	scriptPath: string,
	dayOfWeek: number,
	hour: number = 2,
): string {
	return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${label}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>${scriptPath}</string>
  </array>
  <key>StartCalendarInterval</key>
  <dict>
    <key>Weekday</key>
    <integer>${dayOfWeek}</integer>
    <key>Hour</key>
    <integer>${hour}</integer>
    <key>Minute</key>
    <integer>0</integer>
  </dict>
  <key>StandardOutPath</key>
  <string>${join(homedir(), ".bones", "nightly", "launchd-stdout.log")}</string>
  <key>StandardErrorPath</key>
  <string>${join(homedir(), ".bones", "nightly", "launchd-stderr.log")}</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>/usr/local/bin:/usr/bin:/bin:${join(homedir(), ".bun", "bin")}</string>
  </dict>
</dict>
</plist>`;
}

/**
 * Generates a cron expression for a day/hour combination.
 *
 * @param dayOfWeek - Day of week (0=Sunday)
 * @param hour - Hour (24h)
 * @returns Cron expression
 */
function generateCronLine(
	scriptPath: string,
	dayOfWeek: number,
	hour: number = 2,
): string {
	return `0 ${hour} * * ${dayOfWeek} /bin/bash ${scriptPath}`;
}

/**
 * Generates scheduling configuration for the current platform.
 * Creates wrapper scripts and platform-specific schedule definitions.
 *
 * @param config - Schedule configuration
 * @returns Generated files and setup instructions
 */
export function generateSchedule(config: ScheduleConfig): ScheduleResult {
	const platform = detectPlatform();
	const preset = config.preset ?? "nightly";
	const schedule = getPresetSchedule(preset);
	const projectName = resolve(config.projectPath)
		.split("/")
		.pop()!
		.replace(/[^a-z0-9-]/gi, "-")
		.toLowerCase();

	const scriptsDir = join(homedir(), ".bones", "schedules", projectName);
	const files: Array<{ path: string; content: string }> = [];
	const instructions: string[] = [];

	// Generate wrapper scripts for each scheduled run
	for (const [day, category] of schedule) {
		const dayName = ["sun", "mon", "tue", "wed", "thu", "fri", "sat"][day];
		const scriptName = `bones-${projectName}-${dayName}-${category}.sh`;
		const scriptPath = join(scriptsDir, scriptName);

		files.push({
			path: scriptPath,
			content: buildWrapperScript(config, category),
		});

		if (platform === "macos") {
			const label = `com.bones.${projectName}.${dayName}`;
			const plistPath = join(
				homedir(),
				"Library",
				"LaunchAgents",
				`${label}.plist`,
			);

			files.push({
				path: plistPath,
				content: generatePlist(label, scriptPath, day),
			});

			instructions.push(`launchctl load ${plistPath}`);
		} else {
			instructions.push(generateCronLine(scriptPath, day));
		}
	}

	const setupInstructions =
		platform === "macos"
			? buildMacosInstructions(files, instructions, scriptsDir)
			: buildLinuxInstructions(files, instructions, scriptsDir);

	return { platform, instructions: setupInstructions, files };
}

/**
 * Builds human-readable macOS setup instructions.
 */
function buildMacosInstructions(
	files: ReadonlyArray<{ readonly path: string }>,
	loadCommands: readonly string[],
	scriptsDir: string,
): string {
	const scriptFiles = files.filter((f) => f.path.endsWith(".sh"));
	const plistFiles = files.filter((f) => f.path.endsWith(".plist"));

	const lines = [
		"# Bones Scheduled Runs — macOS (launchd)",
		"",
		"## Generated files:",
		"",
		"### Wrapper scripts:",
		...scriptFiles.map((f) => `  ${f.path}`),
		"",
		"### LaunchAgent plists:",
		...plistFiles.map((f) => `  ${f.path}`),
		"",
		"## Setup:",
		"",
		`1. Make scripts executable:`,
		`   chmod +x ${scriptsDir}/*.sh`,
		"",
		"2. Load the launch agents:",
		...loadCommands.map((cmd) => `   ${cmd}`),
		"",
		"## Management:",
		"",
		"  # List loaded agents",
		"  launchctl list | grep bones",
		"",
		"  # Unload an agent",
		...plistFiles.map((f) => `  launchctl unload ${f.path}`),
		"",
		"  # View logs",
		`  ls ~/.bones/nightly/`,
	];

	return lines.join("\n");
}

/**
 * Builds human-readable Linux setup instructions.
 */
function buildLinuxInstructions(
	files: ReadonlyArray<{ readonly path: string }>,
	cronLines: readonly string[],
	scriptsDir: string,
): string {
	const scriptFiles = files.filter((f) => f.path.endsWith(".sh"));

	const lines = [
		"# Bones Scheduled Runs — Linux (cron)",
		"",
		"## Generated scripts:",
		...scriptFiles.map((f) => `  ${f.path}`),
		"",
		"## Setup:",
		"",
		`1. Make scripts executable:`,
		`   chmod +x ${scriptsDir}/*.sh`,
		"",
		"2. Add to crontab (run `crontab -e` and append):",
		"",
		...cronLines.map((line) => `   ${line}`),
		"",
		"## Management:",
		"",
		"  # View current cron entries",
		"  crontab -l | grep bones",
		"",
		"  # View logs",
		`  ls ~/.bones/nightly/`,
	];

	return lines.join("\n");
}
